### ISSUE TITLE
SENDER NO not decoded from MMS

### ISSUE THREAD

**Issue by gakshay** [heyman/mms-decoder#2]
Great code!

When a MMS is received at get.php, its saved in the DB and listed by list.php. Sender number (from) is not decoded from the MMS.

Can you help me to achieve that? I need to send SMS to both sender and receiver after successful upload of MMS.

Thanks
Akshay  a.k.a gakshay

**Comment by heyman** [comment]
Hi!

Unfortunately, many mobile phones doesn't include the from field when
encoding the MMS messages. Instead this is added by their phone
operator.

/jonatan

On Tue, Jun 28, 2011 at 2:05 PM, gakshay
reply@reply.github.com
wrote:
