### ISSUE TITLE
mms not recieved by get.php

### ISSUE THREAD

**Issue by ajay24x7** [heyman/mms-decoder#3]
I tried to compare your url 
I get this on yours 
Notice: Undefined variable: HTTP_RAW_POST_DATA in /home/jonatan/www_jonatan/heyman.info/mms-decoder/example_application/get.php on line 31
and Blank on mine /get.php
My mobile sends N70 successfully to ur url but keeps trying on mine installation.
Please advice, I also modified php.ini for :always_populate_raw_post_data = On  ;
still no success.
Pleas help, I really like ur script functioning on your site , fast and clean.

**Comment by heyman** [comment]
It sound like it's something wrong with your PHP setup, so I'm closing this issue. If you believe it to be an issue with MMS Decoder, feel free to re-open the issue and provide more details.
